### ISSUE TITLE
Updates for spliced and smeagle

### ISSUE THREAD

**Issue by vsoch** [buildsi/spliced#12]
- spliced: add comment function for pyclingosolver (I can do this)
- spliced: needs to have callsites updated (I can do this)
- smeagle: we aren't doing references to variables (this isn't huge priority)
- Smeagle needs to generalize names for types, need reduced language for primitives
- We don't need to include member functions that appear under a class
- We don't need a fact for a structure, but we need facts for all fields in the structure (but not the structure itself)
- Matt added return types (for 32/64 bit) and there are more complicated cases he didn't get right, e.g., he added a new allocator for return types and it's missing cases.
- exports/imports are all wrong. Things that are functions should start as exported, callsites start as imported, then if we traverse below pointer it becomes import/export (both).
- We need locations to be relative to the parent, e.g., (32+%rdi), recursively created locations
  - fields need a plus
  - pointers get * added
  - make sure not to recurse infinitely 

E.g., 

```
# Integer
fact(Pointer64, %rdi)      # is a pointer to an int
fact(Integer64, *(%rdi)   # is an int

# Structure
struct {
  int8_t a;    # offset 0
  int64_t b;  # offset 8
}
fact(Pointer64, %rdi)     # pointer to struct
fact(Integer64, *(%rdi+0)) --> fact(Integer64, *(%rd))   # we don't want the zero
fact(Integer64, *(%rdi+8)) 
```

If you visit a type that's apointer, it's subtype gets a star
if you visit a type that a struct, the fields get pluses (the current locations plus offsets)

ping @hainest - do you have some time to discuss these in chat?

**Comment by hainest** [comment]
@vsoch Surely. I don't understand some of this.

**Comment by vsoch** [comment]
This is superceded by the enormous amount of work we've done in the last month, seriously amazingly fun and productive @hainest !
